
java_library(
    name = "transitive_foo_user",
    srcs = ["TransitiveFooUser.java"],
    deps =  [
        "//src/main/java/com/example/foo_user",
    ],
    visibility = ["//visibility:public"],
)
